databaseName: sc_pg_db

dataSources:
  sc_pg_db:
    url: jdbc:postgresql://10.19.32.89:31483/postgres
    username: postgres
    password: jjyy7788
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 5

rules:
  - !SINGLE
    tables:
      - "*.*.*"